name: CityDAO Daily Update

on:
  schedule:
    - cron: "01 00 * * *"  # on 7:01 UTC+7
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.4
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
    - name: Run daily proposal update
      run: |
        python run_daily_report.py
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TWITTER_APIKEY: ${{ secrets.TWITTER_APIKEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        GOOGLE_APIKEY: ${{ secrets.GOOGLE_APIKEY }}
